### PR TITLE
Note the end of <details> with horizontal rule

### PR DESCRIPTION
**Pull request by zachahn**
I found it kinda hard to tell where an explanation ends. What do you think about these dividers? I can add more if you like them!

(I realized I accidentally added a block quote. I think that block quotes are too complicated in this context and would suggest horizontal lines!)

### CODE REVIEW

**Comment by changlinli** [comment]
I don't see the division in the rendered Markdown unfortunately :/. It seems to have entirely disappeared? GH's markdown renderer is quite finicky.

**Comment by zachahn** [comment]
Here are some screenshots! I added the thick gray horizontal line. In this case, it's pretty easy to tell where the solution ends, but I found it hard to tell in a few places where there's an explanation or an introduction to some following topic.

### Collapsed

Screenshot 2024-04-04 at 12 49 47 PM

### Expanded

Screenshot 2024-04-04 at 12 48 50 PM

**Comment by changlinli** [comment]
That looks great! If you add the dividers everywhere I'd be happy to merge this in

**Comment by zachahn** [comment]
Updated! I added the horizontal lines to the file we were looking at. I didn't dig around further, but I'm likely to push a similar update the next time I come across other files :)

I seem to have confused GitHub's "rich text diff" though. If you look at the raw diff, you should only see changes related to adding `---`, but the rich diff shows a lot of changed LaTeX (but the few I spot-checked seem to be no-ops?). I admittedly rebased my branch, but I didn't think I did anything too weird!

**Review by changlinli — APPROVED** [review]

**Comment by changlinli** [comment]
Great! Thanks so much!

**Pull request merged**
